name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy with Vercel
        uses: vercel/action@v4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_ajvEh1Dp6nyuk5MhPGUHdMCl
          vercel-project-id: prj_5V1cShbvMhRgw8kA4AfaBJOWFChM
          production: true
